[build]
  command = "npm run build"
  publish = "."
  functions = "functions"

[functions]
  external_node_modules = ["express", "mongoose", "jsonwebtoken", "bcryptjs", "cors"]
  node_bundler = "esbuild"
  included_files = ["routes/**", "models/**", "middleware/**"]

[functions.timeout]
  duration = "30s"

[build.environment]
  NODE_VERSION = "16.19.0"
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 