[build]
  command = "npm install"
  publish = "."
  functions = "functions"

[dev]
  functions = "functions"
  publish = "."

[functions]
  external_node_modules = ["express", "mongoose", "jsonwebtoken", "bcryptjs", "cors"]
  node_bundler = "esbuild"
  included_files = ["routes/**/*", "models/**/*", "middleware/**/*"]

[functions.timeout]
  duration = "30s"

[build.environment]
  NODE_VERSION = "16.19.0"
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
  methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 